### PR TITLE
GetDistance fix

### LINKED ISSUE #44: Bug in GetDistance
I'm sure there is a bug in the GetDistance method.

Some of the distances given are far too big to be correct. We need to properly unit test this method (it's isolated) and determine where the error lies.

### PR DESCRIPTION
**Pull request by mx2s**
#44 
updated function + unit test

### CODE REVIEW

**Review by ardliath — CHANGES_REQUESTED** [review]
Thanks for your help!

Can you add a test to prove what will happen with negative numbers? We had a problem a little bit ago where a single delta gave a negative to be square rooted - that’s why the Abs() functions were there

**Comment by mx2s** [comment]
Everything works, I've checked manually with few numbers + updated unit test

**Review by ardliath — APPROVED** [review]
Thanks for all your help!

**Comment by ardliath** [comment]
Close to kick off CI build

**Pull request merged**
